[[mgr.prepend_keymap]]
desc = "Enter directory"
on = "<Enter>"
run = "enter"

[[mgr.prepend_keymap]]
desc = "Open file with editor"
on = "o"
run = "open"

[[mgr.prepend_keymap]]
desc = "Start bunny.yazi"
on = "b"
run = "plugin bunny"

[[mgr.prepend_keymap]]
desc = "fazif: fd+fzf fuzzy file search"
on = "F"
run = "plugin fazif -- faziffd"

[[mgr.prepend_keymap]]
desc = "fazif: rg+fzf fuzzy content search"
on = "R"
run = "plugin fazif -- fazifrg"
